### ISSUE TITLE
Path for Slurm parsing fork is broken

### ISSUE THREAD

**Issue by verdurin** [WIMM-IT/slurm-analytics#2]
When I try cloning the fork of the AWS Slurm parsing code, the link fails:

```
$ git clone https://github.com/aowenson-imm/hpc-cost-simulator/tree/slurm-sacct-parser
Cloning into 'slurm-sacct-parser'...
fatal: repository 'https://github.com/aowenson-imm/hpc-cost-simulator/tree/slurm-sacct-parser/' not found
```

**Comment by aowenson-imm** [comment]
Correct link should be: https://github.com/aowenson-imm/hpc-cost-simulator

**Comment by verdurin** [comment]
Yes, I should have tried that.

I did find that `GitPython` is required by the `hpc-cost-simulator`, so it would be worth mentioning that too.
