### ISSUE TITLE
Cluster name issue

### ISSUE THREAD

**Issue by verdurin** [WIMM-IT/slurm-analytics#3]
Apologies for the flurry of issues...

Was trying to run the `sacct-parse` step and saw this error:

```
$ python sacct-parse.py -n cluster
No sacct files detected for cluster named 'cluster'
```

**Comment by aowenson-imm** [comment]
That's triggered by this code:

```
pattern = f'Dumps/{cluster_id}/sacct/*.csv'
for input_fp in glob.glob(pattern):
  input_fps.append(input_fp)
if len(input_fps) == 0:
  print(f"No sacct files detected for cluster named '{cluster_id}'")|
 ```
 
 Does folder `Dumps/cluster/sacct` exist, and does it contain csv files? If not, did you run `sacct-dump.py` before?

**Comment by verdurin** [comment]
The folder `Dumps/cluster/resources/` exists, which contains some JSON files.

**Comment by aowenson-imm** [comment]
Based on #1, `sacct-dump.py` did not complete so run it again.

**Comment by verdurin** [comment]
Yes, I did think it was rather quick. That ran properly, then I ran the parse command and saw this, which appears to be in the hpc-cost-simulator. Do I perhaps need to use an older Python?:

```
Parsing: Dumps/cluster/sacct/sacct-output-2024-11-13_2024-11-20.csv
Traceback (most recent call last):
  File "/gpfs3/users/rescomp/<username>/src/github/slurm-analytics/sacct-parse.py", line 87, in <module>
    slurmLogParser = SlurmLogParser.SlurmLogParser(fp, starttime=start, endtime=end)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs3/users/rescomp/<username>/src/github/slurm-analytics/hpc-cost-simulator/SlurmLogParser.py", line 47, in __init__
    super().__init__(None, output_csv, starttime, endtime)
  File "/gpfs3/users/rescomp/<username>/src/github/slurm-analytics/hpc-cost-simulator/SchedulerLogParser.py", line 95, in __init__
    self._starttime_dt = str_to_datetime(self._starttime)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs3/users/rescomp/<username>/src/github/slurm-analytics/hpc-cost-simulator/SchedulerJobInfo.py", line 498, in str_to_datetime
    return datetime.strptime(string_value, SchedulerJobInfo.DATETIME_FORMAT).replace(tzinfo=timezone.utc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/el8/2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/el8/2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-11-13' does not match format '%Y-%m-%dT%H:%M:%S'
```

**Comment by aowenson-imm** [comment]
No, this is my mistake, I forgot my changes to hpc-cost-simulator are in a branch. So run:
> git clone -b slurm-sacct-parser https://github.com/aowenson-imm/hpc-cost-simulator

**Comment by verdurin** [comment]
Yes, that fixed it. I re-ran the dump, just in case.

Now I see lots of errors like this:

ERROR:2024-11-20 13:52:53,332: Dumps/cluster/sacct/sacct-output-2024-11-13_2024-11-20.csv, line 197466: Unable to convert field Timelimit to format td: Partition_Limit: could not convert string to float: 'Partition_Limit'
21477301|<username>|2024-11-13T11:43:22|Partition_Limit|CANCELLED by 38667|gpu_short|None|2024-11-13T12:19:33|00:00:00|0|00:00:00|15565M||0|None assigned|None|10054219|

Here’s the config of that partition:

PartitionName=gpu_short
   AllowGroups=ALL AllowAccounts=ALL AllowQos=ALL
   AllocNodes=ALL Default=NO QoS=N/A
   DefaultTime=NONE DisableRootJobs=NO ExclusiveUser=NO GraceTime=0 Hidden=NO
   MaxNodes=UNLIMITED MaxTime=04:00:00 MinNodes=0 LLN=NO MaxCPUsPerNode=UNLIMITED MaxCPUsPerSocket=UNLIMITED
   Nodes=compg[009-011,013,016,028-032,035-036,039-042]
   PriorityJobFactor=1 PriorityTier=1 RootOnly=NO ReqResv=NO OverSubscribe=NO
   OverTimeLimit=NONE PreemptMode=OFF
   State=UP TotalCPUs=568 TotalNodes=16 SelectTypeParameters=NONE
   JobDefaults=DefCpuPerGPU=6,DefMemPerGPU=62300
   DefMemPerNode=UNLIMITED MaxMemPerNode=UNLIMITED
   TRES=cpu=568,mem=9264754M,node=16,billing=284,gres/gpu=62
   TRESBillingWeights=CPU=0.5,GRES/gpu=4.0



From: aowenson-imm ***@***.***>
Date: Wednesday, 20 November 2024 at 13:18
To: WIMM-IT/slurm-analytics ***@***.***>
Cc: Adam Huffman ***@***.***>, Author ***@***.***>
Subject: Re: [WIMM-IT/slurm-analytics] Cluster name issue (Issue #3)


No, this is my mistake, I forgot my changes to hpc-cost-simulator are in a branch. So run:

git clone -b slurm-sacct-parser https://github.com/aowenson-imm/hpc-cost-simulator

**Comment by aowenson-imm** [comment]
They should be harmless errors - yes the parsing failed for those jobs but they did nothing:
```
Partition_limit
Indicates that the job did not have its time limit set and was not yet subjected to a partition MaxTime (i.e. job is pending).
```
I could reduce the spamminess of output.

Other jobs should have been parsed. Does the parsing compete, creating folder `Parsed/<clustername>/` with pkl files inside?

**Comment by verdurin** [comment]
Here’s the final output:

INFO:2024-11-20 15:30:44,158: Parsed 667528 jobs
ERROR:2024-11-20 15:30:44,158: 49830 errors while parsing jobs
Traceback (most recent call last):
  File "/gpfs3/users/rescomp/<username>/src/github/slurm-analytics/sacct-parse.py", line 91, in <module>
    raise Exception(f'Parsing file created 0 jobs: {fp}')
Exception: Parsing file created 0 jobs: Dumps/cluster/sacct/sacct-output-2024-11-13_2024-11-20.csv

It doesn’t create the ‘Parsed’ folder.



From: aowenson-imm ***@***.***>
Date: Wednesday, 20 November 2024 at 15:25
To: WIMM-IT/slurm-analytics ***@***.***>
Cc: Adam Huffman ***@***.***>, Author ***@***.***>
Subject: Re: [WIMM-IT/slurm-analytics] Cluster name issue (Issue #3)


They should be harmless errors - yes the parsing failed for those jobs but they did nothing:

Partition_limit
Indicates that the job did not have its time limit set and was not yet subjected to a partition MaxTime (i.e. job is pending).


I could reduce the spamminess of output.

Does the parsing compete, creating folder Parsed/<clustername>/?

**Comment by aowenson-imm** [comment]
I've reproduced and fixed, update your clone of `hpc-cost-simulator`.

**Comment by verdurin** [comment]
Yes, final output is now:
```
INFO:2024-11-20 16:34:29,500: Parsed 667528 jobs
ERROR:2024-11-20 16:34:29,500: 49830 errors while parsing jobs
- dropping 12 incomplete jobs
```
and the `Parsed` folder is created.

Thanks.
